### ISSUE TITLE
A question

### ISSUE THREAD

**Issue by zymize** [RayXie29/GridMask_Tensorflow#1]
Hello,when I run this work,I  get a problem.I use tensorflow1.14,is this version problem?

Traceback (most recent call last):
  File "D:/daima/GridMask_Tensorflow-master/main.py", line 32, in <module>
    daisy_masked = apply_grid_mask(daisy, daisy.get_shape().as_list(), 90, 150, 23, 0.5)
  File "D:/daima/GridMask_Tensorflow-master/main.py", line 6, in apply_grid_mask
    mask = GridMask(image_shape[0], image_shape[1], d1, d2, rotate_angle, ratio)
  File "D:\daima\GridMask_Tensorflow-master\gridmask_tf.py", line 8, in GridMask
    hh = int(np.ceil(np.sqrt(h*h+w*w)))
TypeError: unsupported operand type(s) for *: 'NoneType' and 'NoneType'

thanks.

**Comment by RayXie29** [comment]
Yes, please use this function in Tensorflow with version equal or above 2.0.0.
